"""
Lightweight prototype of autonomous UI design agent.
Uses OpenAI GPT-4o for image analysis and generates HTML/CSS.
"""
import os
import base64
import json
import sys
from pathlib import Path
from PIL import Image, ImageDraw, ImageFont
import openai
import requests

# Configuration
OPENAI_API_KEY = os.environ.get("API_KEY_OPENAI")
if not OPENAI_API_KEY:
    print("ERROR: API_KEY_OPENAI environment variable not set.")
    sys.exit(1)

client = openai.OpenAI(api_key=OPENAI_API_KEY)

# 1. Create a test UI screenshot (if not exists)
def create_test_image(output_path="test_ui.png"):
    """Generate a simple mock UI screenshot for testing."""
    img = Image.new('RGB', (800, 600), color='#1e293b')
    draw = ImageDraw.Draw(img)
    
    # Draw a header
    draw.rectangle([0, 0, 800, 60], fill='#0f172a')
    draw.text((20, 20), "Dashboard", fill='#f1f5f9', font=ImageFont.load_default())
    
    # Draw a card
    draw.rectangle([50, 100, 350, 300], fill='#334155', outline='#475569', width=2)
    draw.text((70, 120), "Card Title", fill='#e2e8f0', font=ImageFont.load_default())
    draw.text((70, 150), "This is a sample UI card.", fill='#94a3b8')
    
    # Draw a button
    draw.rectangle([70, 200, 200, 240], fill='#3b82f6')
    draw.text((90, 205), "Primary Button", fill='white')
    
    # Draw a sidebar
    draw.rectangle([0, 60, 200, 600], fill='#0f172a')
    
    img.save(output_path)
    print(f"Generated test image: {output_path}")
    return output_path

# 2. Analyze image with GPT-4o
def analyze_ui(image_path):
    """Send image to GPT-4o and extract design system."""
    print(f"Analyzing {image_path} with GPT-4o...")
    
    with open(image_path, "rb") as f:
        image_data = f.read()
    image_b64 = base64.b64encode(image_data).decode("utf-8")
    
    system_prompt = """You are a UI/UX design expert. Analyze the provided screenshot of a user interface.
Extract a design system in JSON format with the following structure:
{
  "theme_name": "Descriptive name",
  "palette": {
    "primary": "#hex",
    "secondary": "#hex",
    "background": "#hex",
    "surface": "#hex",
    "text_primary": "#hex",
    "text_secondary": "#hex"
  },
  "typography": {
    "font_family_heading": "Font name",
    "font_family_body": "Font name"
  },
  "layout": {
    "border_radius": "px",
    "spacing_unit": "px"
  },
  "observations": ["List of key visual characteristics"]
}
Provide ONLY valid JSON. No additional text."""
    
    try:
        response = client.chat.completions.create(
            model="gpt-4o",
            messages=[
                {"role": "system", "content": system_prompt},
                {"role": "user", "content": [
                    {"type": "text", "text": "Analyze this UI screenshot and extract the design system."},
                    {"type": "image_url", "image_url": {"url": f"data:image/jpeg;base64,{image_b64}"}}
                ]}
            ],
            temperature=0.1,
            max_tokens=1500
        )
        
        result_text = response.choices[0].message.content
        # Extract JSON
        import re
        json_match = re.search(r'```json\n(.*?)\n```', result_text, re.DOTALL)
        if json_match:
            result_text = json_match.group(1)
        else:
            json_match = re.search(r'\{.*\}', result_text, re.DOTALL)
            if json_match:
                result_text = json_match.group(0)
        
        design_system = json.loads(result_text)
        print("Design system extracted successfully.")
        return design_system
    
    except Exception as e:
        print(f"Error in analysis: {e}")
        return None

# 3. Generate HTML/CSS from design system
def generate_code(design_system, output_dir="generated"):
    """Generate HTML and CSS files based on design system."""
    os.makedirs(output_dir, exist_ok=True)
    
    palette = design_system.get("palette", {})
    theme_name = design_system.get("theme_name", "AI Generated Theme")
    
    # CSS file
    css = f"""/* {theme_name} - Generated by AI */
:root {{
  --primary: {palette.get('primary', '#3b82f6')};
  --secondary: {palette.get('secondary', '#64748b')};
  --background: {palette.get('background', '#0f172a')};
  --surface: {palette.get('surface', '#1e293b')};
  --text-primary: {palette.get('text_primary', '#f1f5f9')};
  --text-secondary: {palette.get('text_secondary', '#94a3b8')};
  --border-radius: {design_system.get('layout', {}).get('border_radius', '8px')};
  --spacing-unit: {design_system.get('layout', {}).get('spacing_unit', '16px')};
}}

* {{
  margin: 0;
  padding: 0;
  box-sizing: border-box;
}}

body {{
  font-family: '{design_system.get('typography', {}).get('font_family_body', 'Inter')}', sans-serif;
  background-color: var(--background);
  color: var(--text-primary);
  line-height: 1.6;
  padding: var(--spacing-unit);
}}

h1, h2, h3, h4 {{
  font-family: '{design_system.get('typography', {}).get('font_family_heading', 'Inter')}', sans-serif;
  font-weight: 700;
}}

.container {{
  max-width: 1200px;
  margin: 0 auto;
}}

.header {{
  background-color: var(--surface);
  padding: calc(var(--spacing-unit) * 2);
  border-radius: var(--border-radius);
  margin-bottom: var(--spacing-unit);
}}

.card {{
  background-color: var(--surface);
  border-radius: var(--border-radius);
  padding: var(--spacing-unit);
  margin-bottom: var(--spacing-unit);
  box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);
}}

.btn-primary {{
  background-color: var(--primary);
  color: white;
  border: none;
  padding: 12px 24px;
  border-radius: var(--border-radius);
  cursor: pointer;
  font-weight: 600;
}}

.btn-secondary {{
  background-color: transparent;
  color: var(--primary);
  border: 2px solid var(--primary);
  padding: 12px 24px;
  border-radius: var(--border-radius);
  cursor: pointer;
  font-weight: 600;
}}
"""
    
    # HTML file
    html = f"""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{theme_name}</title>
  <link rel="stylesheet" href="style.css">
  <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;700&display=swap" rel="stylesheet">
</head>
<body>
  <div class="container">
    <header class="header">
      <h1>{theme_name}</h1>
      <p>This page was generated automatically from an AI‑analyzed design system.</p>
    </header>
    
    <main>
      <section class="card">
        <h2>Color Palette</h2>
        <div style="display: flex; gap: 16px; margin-top: 20px;">
          <div style="background-color: {palette.get('primary', '#3b82f6')}; width: 60px; height: 60px; border-radius: 8px;"></div>
          <div style="background-color: {palette.get('secondary', '#64748b')}; width: 60px; height: 60px; border-radius: 8px;"></div>
          <div style="background-color: {palette.get('background', '#0f172a')}; width: 60px; height: 60px; border-radius: 8px; border: 1px solid #333;"></div>
          <div style="background-color: {palette.get('surface', '#1e293b')}; width: 60px; height: 60px; border-radius: 8px;"></div>
        </div>
        <p>Primary: <code>{palette.get('primary', '#3b82f6')}</code></p>
      </section>
      
      <section class="card">
        <h2>Components</h2>
        <button class="btn-primary">Primary Button</button>
        <button class="btn-secondary" style="margin-left: 12px;">Secondary Button</button>
      </section>
      
      <section class="card">
        <h2>Design System JSON</h2>
        <pre style="background-color: #111; padding: 16px; border-radius: 8px; overflow: auto;">
{json.dumps(design_system, indent=2)}
        </pre>
      </section>
    </main>
    
    <footer style="margin-top: 40px; text-align: center; color: var(--text-secondary);">
      <p>Generated by AgentZero UI Autonomous Agent • {theme_name}</p>
    </footer>
  </div>
</body>
</html>
"""
    
    css_path = os.path.join(output_dir, "style.css")
    html_path = os.path.join(output_dir, "index.html")
    
    with open(css_path, "w") as f:
        f.write(css)
    with open(html_path, "w") as f:
        f.write(html)
    
    print(f"Generated files in {output_dir}/:")
    print(f"  - {css_path}")
    print(f"  - {html_path}")
    
    return {"css": css_path, "html": html_path}

# Main workflow
def main():
    print("=== Lightweight UI Autonomous Agent Prototype ===")
    
    # Step 1: Create or use test image
    test_image = "test_ui.png"
    if not os.path.exists(test_image):
        create_test_image(test_image)
    else:
        print(f"Using existing test image: {test_image}")
    
    # Step 2: Analyze
    design_system = analyze_ui(test_image)
    if not design_system:
        print("Analysis failed. Exiting.")
        return
    
    print("\nExtracted Design System:")
    print(json.dumps(design_system, indent=2))
    
    # Step 3: Generate code
    print("\nGenerating code...")
    generated = generate_code(design_system)
    
    print("\n✅ Prototype completed successfully!")
    print(f"Open {generated['html']} in your browser to see the result.")

if __name__ == "__main__":
    main()
